"""PDF Report Generator — creates a downloadable investment report."""

from __future__ import annotations

from fpdf import FPDF
from io import BytesIO

from app.models import FinalRecommendation


def _sanitize_text(text: str) -> str:
    """Sanitize text for fpdf2 by replacing unsupported Unicode characters."""
    replacements = {
        "\u2014": "-",      # em-dash
        "\u2013": "-",      # en-dash
        "\u201c": '"',      # left smart quote
        "\u201d": '"',      # right smart quote
        "\u2018": "'",      # left smart single quote
        "\u2019": "'",      # right smart single quote
        "\u2026": "...",    # ellipsis
        "\u2022": "*",      # bullet point
        "\u2192": "->",     # arrow
        "\u2190": "<-",     # left arrow
        "\u2265": ">=",     # greater than or equal
        "\u2264": "<=",     # less than or equal
        "\u2260": "!=",     # not equal
        "\u00b7": "*",      # middle dot
        "\u2012": "-",      # figure dash
        "\u2015": "-",      # horizontal bar
        "\u201e": '"',      # double low-9 quotation mark
        "\u201a": "'",      # single low-9 quotation mark
    }
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)
    # Fallback: replace any remaining non-latin1 characters
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text


def generate_pdf(rec: FinalRecommendation) -> bytes:
    """Generate a PDF report from a FinalRecommendation.

    Returns PDF as bytes (suitable for Streamlit download button).
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "Investment Research Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Ticker + Company
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"{rec.ticker} - {rec.company_name}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # Recommendation box
    pdf.set_font("Helvetica", "B", 14)
    color_map = {"Buy": (34, 139, 34), "Sell": (220, 20, 60), "Hold": (255, 165, 0)}
    r, g, b = color_map.get(rec.recommendation, (0, 0, 0))
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 10, f"Recommendation: {rec.recommendation}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)

    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Confidence: {rec.confidence}%", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # Divider
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Sentiment
    _section(pdf, "Sentiment")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, _sanitize_text(rec.sentiment))
    pdf.ln(5)

    # Rationale
    _section(pdf, "Rationale")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, _sanitize_text(rec.rationale))
    pdf.ln(5)

    # Key Metrics
    if rec.key_metrics:
        _section(pdf, "Key Metrics")
        pdf.set_font("Helvetica", "", 11)
        for key, value in rec.key_metrics.items():
            label = key.replace("_", " ").title()
            pdf.cell(0, 6, f"  {label}: {value}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

    # Caveats
    if rec.caveats:
        _section(pdf, "Risk Caveats")
        pdf.set_font("Helvetica", "", 11)
        for caveat in rec.caveats:
            pdf.cell(0, 6, f"  * {_sanitize_text(caveat)}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

    # Disclaimer
    pdf.ln(10)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0, 4,
        _sanitize_text(
            "Disclaimer: This report is generated by an AI system for educational purposes only. "
            "It does not constitute financial advice. Always consult a qualified financial advisor "
            "before making investment decisions. Past performance does not guarantee future results."
        ),
    )

    return bytes(pdf.output())


def _section(pdf: FPDF, title: str) -> None:
    """Helper to render a section header."""
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
